version: '3'
volumes:
  user-data:
services:
  db_register:
    image: mysql:8.0
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: register_db
      MYSQL_USER: register_user
      MYSQL_PASSWORD: register_pwd
    ports:
      - "3309:3306"
#
#  app:
#    image: openjdk:8
#    restart: always
#    working_dir: /app
#    volumes:
#    - ../application/build/libs:/app
#    - ~/.m2:/root/.m2
#    expose:
#    - "8080"
#    command:  java -jar register-api-application-1.0.0-REALEASE.jar
#    depends_on:
#    - db_register
#    ports:
#    - "8080:8080"